<template>
  <view class="page-shell"><view class="page-content"><view class="summary-card"><view><text class="summary-title">服务管理</text><text class="summary-desc">服务创建与审核将在下一阶段接入</text></view><view class="summary-count">12</view></view><view class="status-grid"><view v-for="item in statuses" :key="item.label" class="status-card"><text class="status-value" :class="item.tone">{{ item.value }}</text><text class="status-label">{{ item.label }}</text></view></view><view class="placeholder-card"><u-icon name="grid" size="42" color="#98A5B3" /><text class="placeholder-title">服务管理基础入口已建立</text><text class="placeholder-desc">后续将支持草稿、规格编辑、提交审核、驳回修改和上下架。</text></view></view><role-tab-bar :tabs="MERCHANT_TABS" current="/subpkg-merchant/services/index" /></view>
</template>
<script setup>
import { onShow } from '@dcloudio/uni-app'
import RoleTabBar from '@/components/base/role-tab-bar.vue'
import { MERCHANT_TABS } from '@/constants/merchant-navigation.js'
import { ROLES } from '@/constants/roles.js'
import { requireRole } from '@/utils/permission.js'
const statuses = [{ label: '已上架', value: 8, tone: 'green' }, { label: '审核中', value: 2, tone: 'blue' }, { label: '已驳回', value: 1, tone: 'orange' }, { label: '草稿', value: 1, tone: 'grey' }]
onShow(() => requireRole(ROLES.MERCHANT_MEMBER))
</script>
<style lang="scss" scoped>
.page-shell { min-height: 100vh; background: $page-gradient; }.page-content { padding: 28rpx $spacing-base calc(140rpx + env(safe-area-inset-bottom)); }.summary-card { display: flex; align-items: center; justify-content: space-between; min-height: 180rpx; padding: 30rpx; border-radius: 32rpx; background: linear-gradient(135deg,#116b68,#00a89d 55%,#38c6b5); color: #fff; box-shadow: $shadow-float; }.summary-title,.summary-desc { display: block; }.summary-title { font-size: 35rpx; font-weight: 700; }.summary-desc { margin-top: 8rpx; font-size: $font-size-xs; opacity: .8; }.summary-count { display: flex; align-items: center; justify-content: center; width: 88rpx; height: 88rpx; border-radius: 28rpx; background: rgba(255,255,255,.18); font-size: 36rpx; font-weight: 700; }.status-grid { display: grid; grid-template-columns: repeat(4,1fr); gap: 12rpx; margin-top: 20rpx; }.status-card { padding: 21rpx 4rpx; border: $glass-border-soft; border-radius: 22rpx; background: $surface-gradient; text-align: center; }.status-value,.status-label { display: block; }.status-value { font-size: 32rpx; font-weight: 700; }.green { color: $success-color; }.blue { color: $primary-color; }.orange { color: $warning-color; }.grey { color: $info-color; }.status-label { margin-top: 5rpx; color: $text-color-hint; font-size: 19rpx; }.placeholder-card { display: flex; flex-direction: column; align-items: center; margin-top: 24rpx; padding: 70rpx 36rpx; border: $glass-border-soft; border-radius: 28rpx; background: $surface-gradient; box-shadow: $shadow-sm; text-align: center; }.placeholder-title,.placeholder-desc { display: block; }.placeholder-title { margin-top: 20rpx; color: $text-color; font-size: $font-size-base; font-weight: 600; }.placeholder-desc { margin-top: 10rpx; color: $text-color-hint; font-size: $font-size-xs; line-height: 1.6; }
</style>
