<template>
  <view v-if="order" class="page-shell">
    <view class="status-card" :class="`tone-${statusMeta.tone}`"><view><text class="status-title">{{ statusMeta.text }}</text><text class="status-desc">{{ statusDescription }}</text></view><u-icon :name="statusMeta.icon || 'clock-fill'" size="44" color="rgba(255,255,255,.92)" /></view>
    <view class="detail-card"><text class="card-title">服务与顾客</text><view class="service-head"><view class="service-icon"><u-icon name="heart-fill" size="27" color="#3A7BF7" /></view><view class="service-copy"><text class="service-name">{{ order.serviceItemName }}</text><text class="secondary">{{ order.specName }} · ¥{{ order.totalAmount }}</text></view></view><view class="info-row"><text class="label">预约时间</text><text class="value">{{ order.serviceDate }} {{ slotText(order.serviceTimeSlot) }}</text></view><view class="info-row"><text class="label">联系人</text><text class="value">{{ order.receiverName }} {{ order.receiverPhone }}</text></view><view class="info-row"><text class="label">服务地址</text><text class="value multiline">{{ order.addressDetail }}</text></view><view v-if="order.remark" class="notice-box"><u-icon name="info-circle" size="18" color="#FF8A5C" /><text>{{ order.remark }}</text></view></view>
    <view class="detail-card"><view class="card-heading"><text class="card-title no-margin">护理人员</text><text v-if="canDispatch" class="card-link" @click="goDispatch">{{ order.assignments?.length ? '重新派单' : '立即派单' }}</text></view><view v-if="order.currentAssignment" class="caregiver-row"><view class="caregiver-avatar"><u-icon name="server-man" size="27" color="#3A7BF7" /></view><view class="caregiver-copy"><text class="caregiver-name">{{ order.currentAssignment.caregiverName }}</text><text class="secondary">{{ assignmentText(order.assignmentStatus) }}</text></view><text>{{ order.currentAssignment.caregiverPhone }}</text></view><view v-else class="empty-assignment">当前尚未安排护理人员</view></view>
    <view v-if="order.assignments?.length" class="detail-card"><text class="card-title">派单记录</text><view v-for="assignment in order.assignments" :key="assignment.assignmentId" class="record-row"><view><text class="record-title">{{ assignment.caregiverName }}</text><text v-if="assignment.rejectReason" class="record-summary">拒绝原因：{{ assignment.rejectReason }}</text><text class="record-time">{{ formatTime(assignment.dispatchTime) }}</text></view><text class="record-status">{{ assignmentText(assignment.status) }}</text></view></view>
    <view v-if="order.serviceRecords?.length" class="detail-card"><text class="card-title">履约记录</text><view v-for="record in order.serviceRecords" :key="record.recordId" class="record-row"><view><text class="record-title">{{ record.content }}</text><text v-if="record.summary" class="record-summary">{{ record.summary }}</text><text class="record-time">{{ formatTime(record.createTime) }}</text></view><text v-if="record.abnormal" class="warning-text">异常签到</text></view></view>
    <view v-if="order.operationLogs?.length" class="detail-card"><text class="card-title">订单进度</text><view v-for="log in order.operationLogs" :key="`${log.action}-${log.createTime}`" class="timeline-row"><view class="timeline-dot" /><view><text class="record-title">{{ log.remark }}</text><text class="record-time">{{ formatTime(log.createTime) }}</text></view></view></view>
  </view>
  <view v-else class="loading-page"><u-loading-icon size="32" color="#3A7BF7" /></view>
</template>

<script setup>
import { computed } from 'vue'
import { onLoad, onShow } from '@dcloudio/uni-app'
import { ASSIGNMENT_STATUS, ORDER_STATUS, getOrderStatusMeta } from '@/constants/order-status.js'
import { ROLES } from '@/constants/roles.js'
import { useMerchantStore } from '@/store/merchant.js'
import { requireRole } from '@/utils/permission.js'

const merchantStore = useMerchantStore()
let orderId = null
const order = computed(() => merchantStore.currentOrder)
const canDispatch = computed(() => order.value?.orderStatus === ORDER_STATUS.WAITING_DISPATCH && [ASSIGNMENT_STATUS.UNASSIGNED, ASSIGNMENT_STATUS.REJECTED, ASSIGNMENT_STATUS.EXPIRED].includes(order.value?.assignmentStatus))
const statusMeta = computed(() => { if (canDispatch.value) return { text: '待派单', tone: 'warning', icon: 'share' }; if (order.value?.assignmentStatus === ASSIGNMENT_STATUS.WAITING_ACCEPT) return { text: '待接单', tone: 'warning', icon: 'bell-fill' }; return getOrderStatusMeta(order.value || {}) })
const statusDescription = computed(() => ({ WAITING_DISPATCH: canDispatch.value ? '请选择合适的护理人员完成派单' : '等待护理人员接受任务', WAITING_SERVICE: '护理人员已接单，等待按时上门', IN_SERVICE: '护理服务正在进行中', WAITING_CONFIRM: '护理人员已结束服务，等待顾客确认', COMPLETED: '订单已经完成' }[order.value?.orderStatus] || statusMeta.value.description || '订单状态已更新'))
onLoad(async (options) => { if (!requireRole(ROLES.MERCHANT_MEMBER)) return; orderId = Number(options.id); await merchantStore.fetchOrderDetail(orderId) })
onShow(async () => { if (orderId) await merchantStore.fetchOrderDetail(orderId) })
function slotText(slot) { return ({ MORNING: '上午 08:00-12:00', AFTERNOON: '下午 13:00-17:00', EVENING: '晚上 18:00-21:00' }[slot] || slot) }
function formatTime(value) { return value ? value.replace('T', ' ').replace('+08:00', '').slice(0, 16) : '--' }
function assignmentText(status) { return ({ UNASSIGNED: '待派单', WAITING_ACCEPT: '等待接单', ACCEPTED: '已接单', REJECTED: '已拒绝', EXPIRED: '已过期', CANCELED: '已取消' }[status] || '未知') }
function goDispatch() { uni.navigateTo({ url: `/subpkg-merchant/dispatch/index?id=${order.value.orderId}&mode=${order.value.assignments?.length ? 'redispatch' : 'dispatch'}` }) }
</script>

<style lang="scss" scoped>
.page-shell { min-height: 100vh; padding: 24rpx $spacing-base 60rpx; background: $page-gradient; }.loading-page { min-height: 100vh; display: flex; align-items: center; justify-content: center; background: $page-gradient; }.status-card { display: flex; align-items: center; justify-content: space-between; min-height: 170rpx; padding: 30rpx; border-radius: 30rpx; color: #fff; box-shadow: $shadow-float; }.tone-warning { background: linear-gradient(135deg,#ff9a6c,#ff7b55); }.tone-primary { background: $primary-gradient; }.tone-success { background: linear-gradient(135deg,#00a99d,#2dd4bf); }.tone-neutral { background: linear-gradient(135deg,#728096,#9aa7b7); }.status-title,.status-desc { display: block; }.status-title { font-size: 40rpx; font-weight: 700; }.status-desc { margin-top: 9rpx; font-size: $font-size-sm; opacity: .84; }
.detail-card { margin-top: 20rpx; padding: 26rpx 24rpx; border: $glass-border-soft; border-radius: 28rpx; background: $surface-gradient; box-shadow: $shadow-sm; }.card-heading { display: flex; align-items: center; justify-content: space-between; margin-bottom: 20rpx; }.card-title { display: block; margin-bottom: 21rpx; color: $text-color; font-size: $font-size-md; font-weight: 700; }.card-title.no-margin { margin-bottom: 0; }.card-link { color: $primary-color; font-size: $font-size-sm; }.service-head { display: flex; align-items: center; gap: 16rpx; margin-bottom: 14rpx; padding-bottom: 20rpx; border-bottom: 1rpx solid $divider-color; }.service-icon { display: flex; align-items: center; justify-content: center; width: 74rpx; height: 74rpx; border-radius: 23rpx; background: $primary-bg; }.service-copy { flex: 1; }.service-name,.secondary { display: block; }.service-name { color: $text-color; font-size: 30rpx; font-weight: 700; }.secondary { margin-top: 5rpx; color: $text-color-hint; font-size: $font-size-xs; }.info-row { display: flex; justify-content: space-between; gap: 28rpx; padding: 14rpx 0; }.label { flex-shrink: 0; color: $text-color-hint; font-size: $font-size-sm; }.value { color: $text-color-secondary; font-size: $font-size-sm; text-align: right; }.value.multiline { line-height: 1.6; }.notice-box { display: flex; align-items: flex-start; gap: 10rpx; margin-top: 14rpx; padding: 17rpx; border-radius: 18rpx; background: #fff2eb; color: $text-color-secondary; font-size: $font-size-xs; line-height: 1.5; }
.caregiver-row { display: flex; align-items: center; gap: 15rpx; }.caregiver-avatar { display: flex; align-items: center; justify-content: center; width: 70rpx; height: 70rpx; border-radius: 22rpx; background: $primary-bg; }.caregiver-copy { flex: 1; }.caregiver-name { display: block; color: $text-color; font-size: $font-size-base; font-weight: 600; }.empty-assignment { padding: 25rpx; border-radius: 20rpx; background: $bg-color-grey; color: $text-color-hint; font-size: $font-size-sm; text-align: center; }.record-row { display: flex; align-items: flex-start; justify-content: space-between; gap: 18rpx; padding: 18rpx 0; border-bottom: 1rpx solid $divider-color; }.record-row:last-child { border-bottom: none; }.record-title,.record-summary,.record-time { display: block; }.record-title { color: $text-color-secondary; font-size: $font-size-sm; }.record-summary { margin-top: 6rpx; color: $text-color-hint; font-size: $font-size-xs; }.record-time { margin-top: 7rpx; color: $text-color-disabled; font-size: $font-size-xs; }.record-status { color: $primary-color; font-size: $font-size-xs; }.warning-text { color: $warning-color; font-size: $font-size-xs; }.timeline-row { display: flex; gap: 14rpx; padding-bottom: 24rpx; }.timeline-row:last-child { padding-bottom: 0; }.timeline-dot { width: 17rpx; height: 17rpx; margin-top: 5rpx; flex-shrink: 0; border: 4rpx solid rgba(58,123,247,.2); border-radius: 50%; background: $primary-color; }
</style>
