<template>
  <view v-if="order" class="page-shell">
    <view class="status-card" :class="`tone-${statusMeta.tone}`"><view><text class="status-title">{{ statusMeta.text }}</text><text class="status-desc">{{ statusMeta.description }}</text></view><u-icon :name="statusMeta.icon" size="46" color="rgba(255,255,255,0.9)" /></view>
    <view class="detail-card"><text class="card-title">服务信息</text><view class="service-row"><view class="service-icon"><u-icon name="heart-fill" size="28" color="#3A7BF7" /></view><view class="service-copy"><text class="service-name">{{ order.serviceItemName }}</text><text class="secondary">{{ order.specName }}</text></view><text class="amount">¥{{ order.totalAmount }}</text></view></view>
    <view v-if="order.merchantName || order.currentAssignment" class="detail-card"><text class="card-title">服务方信息</text><view v-if="order.merchantName" class="info-row"><text class="label">服务商户</text><text class="value">{{ order.merchantName }}</text></view><view v-if="order.currentAssignment" class="caregiver-profile"><view class="caregiver-avatar"><u-icon name="server-man" size="28" color="#3A7BF7" /></view><view class="caregiver-copy"><text class="caregiver-name">{{ order.currentAssignment.caregiverName }}</text><text class="secondary">{{ assignmentText(order.assignmentStatus) }}</text></view><text class="caregiver-phone">{{ order.currentAssignment.caregiverPhone }}</text></view></view>
    <view class="detail-card"><text class="card-title">预约信息</text><view class="info-row"><text class="label">服务时间</text><text class="value">{{ order.serviceDate }} {{ orderStore.getSlotText(order.serviceTimeSlot) }}</text></view><view class="info-row"><text class="label">联系人</text><text class="value">{{ order.receiverName }} {{ order.receiverPhone }}</text></view><view class="info-row"><text class="label">服务地址</text><text class="value multiline">{{ order.addressDetail }}</text></view><view v-if="order.remark" class="info-row"><text class="label">备注</text><text class="value multiline">{{ order.remark }}</text></view></view>
    <view v-if="order.assignments?.length" class="detail-card"><text class="card-title">派单记录</text><view v-for="assignment in order.assignments" :key="assignment.assignmentId" class="record-row"><view><text class="record-title">{{ assignment.caregiverName }}</text><text class="record-time">{{ formatTime(assignment.dispatchTime) }}</text></view><text class="record-status">{{ assignmentText(assignment.status) }}</text></view></view>
    <view v-if="order.serviceRecords?.length" class="detail-card"><text class="card-title">服务记录</text><view v-for="record in order.serviceRecords" :key="record.recordId" class="record-row service-record"><view><text class="record-title">{{ record.content }}</text><text v-if="record.summary" class="record-summary">{{ record.summary }}</text><text class="record-time">{{ formatTime(record.createTime) }}</text></view><text v-if="record.distanceMeters !== undefined" class="record-status">距地址 {{ record.distanceMeters }}m</text></view></view>
    <view class="detail-card"><text class="card-title">订单信息</text><view class="info-row"><text class="label">订单编号</text><text class="value">{{ order.orderNo }}</text></view><view class="info-row"><text class="label">创建时间</text><text class="value">{{ formatTime(order.createTime) }}</text></view><view class="info-row"><text class="label">服务费用</text><text class="value price">¥{{ order.totalAmount }}</text></view></view>
    <view v-if="order.operationLogs?.length" class="detail-card"><text class="card-title">订单进度</text><view class="timeline"><view v-for="(log, index) in order.operationLogs" :key="`${log.action}-${index}`" class="timeline-item"><view class="timeline-mark"><view class="dot" /><view v-if="index < order.operationLogs.length - 1" class="line" /></view><view class="timeline-copy"><text class="timeline-title">{{ log.remark }}</text><text class="timeline-time">{{ formatTime(log.createTime) }}</text></view></view></view></view>
    <view class="bottom-actions">
      <button v-if="orderStore.canCustomerPay(order)" class="action-btn primary" @click="pay">立即支付</button>
      <button v-if="orderStore.canCustomerCancel(order)" class="action-btn" @click="cancel">取消订单</button>
      <button v-if="orderStore.canCustomerReview(order)" class="action-btn primary" @click="review">评价服务</button>
      <button v-if="orderStore.canCustomerConfirm(order)" class="action-btn primary" @click="confirm">确认完成</button>
      <button v-if="orderStore.canCustomerComplain(order)" class="action-btn" @click="complaint">投诉反馈</button>
      <button v-if="order.serviceItemId" class="action-btn" @click="bookAgain">再次预约</button>
    </view>
  </view>
  <view v-else class="loading-page"><u-loading-icon size="32" color="#3A7BF7" /></view>
</template>

<script setup>
import { computed, ref } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import { useOrderStore } from '@/store/order.js'

const orderStore = useOrderStore()
const order = ref(null)
const statusMeta = computed(() => orderStore.getStatusMeta(order.value || {}))
onLoad(async (options) => { order.value = await orderStore.fetchOrderDetail(Number(options.id)) })
function formatTime(value) { return value ? value.replace('T', ' ').replace('+08:00', '').slice(0, 16) : '--' }
async function pay() { try { const payment = await orderStore.executePayment(order.value.orderId); const status = payment.success ? 'success' : 'failed'; uni.redirectTo({ url: `/pages/payment-result/payment-result?status=${status}&orderId=${order.value.orderId}&amount=${order.value.totalAmount}` }) } catch { uni.redirectTo({ url: `/pages/payment-result/payment-result?status=failed&orderId=${order.value.orderId}&amount=${order.value.totalAmount}` }) } }
function cancel() { uni.showModal({ title: '取消订单', content: '确定取消本次护理服务吗？', success: async ({ confirm }) => { if (confirm) order.value = await orderStore.cancelOrder(order.value.orderId, '用户主动取消').then(() => orderStore.fetchOrderDetail(order.value.orderId)) } }) }
function review() { uni.navigateTo({ url: `/pages/review/review-submit?orderId=${order.value.orderId}` }) }
function complaint() { uni.navigateTo({ url: `/pages/complaint/complaint-submit?orderId=${order.value.orderId}` }) }
async function confirm() { await orderStore.confirmOrder(order.value.orderId); order.value = await orderStore.fetchOrderDetail(order.value.orderId) }
function bookAgain() { uni.navigateTo({ url: `/pages/booking/booking?itemId=${order.value.serviceItemId}&specId=${order.value.serviceSpecId || ''}` }) }
function assignmentText(status) { return ({ UNASSIGNED: '待派单', WAITING_ACCEPT: '等待护理人员接单', ACCEPTED: '护理人员已接单', REJECTED: '护理人员已拒绝', EXPIRED: '派单已过期', CANCELED: '派单已取消' }[status] || '状态未知') }
</script>

<style lang="scss" scoped>
.page-shell { min-height: 100vh; padding: 24rpx $spacing-base 170rpx; background: $page-gradient; }.status-card { display: flex; align-items: center; justify-content: space-between; min-height: 170rpx; padding: 30rpx; border-radius: 30rpx; color: #fff; box-shadow: $shadow-float; }.tone-warning { background: linear-gradient(135deg,#ff9a6c,#ff7b55); }.tone-primary { background: $primary-gradient; }.tone-success { background: linear-gradient(135deg,#00a99d,#2dd4bf); }.tone-neutral { background: linear-gradient(135deg,#728096,#9aa7b7); }.status-title { display: block; font-size: 40rpx; font-weight: 700; }.status-desc { display: block; margin-top: 10rpx; font-size: $font-size-sm; opacity: 0.82; }
.detail-card { margin-top: 20rpx; padding: 26rpx 24rpx; border: $glass-border-soft; border-radius: 28rpx; background: $surface-gradient; box-shadow: $shadow-sm; }.card-title { display: block; margin-bottom: 22rpx; color: $text-color; font-size: $font-size-md; font-weight: 700; }.service-row { display: flex; align-items: center; gap: 16rpx; }.service-icon { width: 76rpx; height: 76rpx; display: flex; align-items: center; justify-content: center; border-radius: 24rpx; background: $primary-bg; }.service-copy { flex: 1; }.service-name { display: block; color: $text-color; font-size: 30rpx; font-weight: 700; }.secondary { display: block; margin-top: 6rpx; color: $text-color-hint; font-size: $font-size-xs; }.amount,.price { color: $warning-color !important; font-size: 34rpx; font-weight: 700; }
.info-row { display: flex; justify-content: space-between; gap: 28rpx; padding: 15rpx 0; }.label { flex-shrink: 0; color: $text-color-hint; font-size: $font-size-sm; }.value { color: $text-color-secondary; font-size: $font-size-sm; text-align: right; }.value.multiline { line-height: 1.6; }
.timeline-item { display: flex; min-height: 92rpx; }.timeline-mark { position: relative; width: 34rpx; flex-shrink: 0; }.dot { width: 18rpx; height: 18rpx; margin-top: 5rpx; border: 5rpx solid rgba(58,123,247,0.2); border-radius: 50%; background: $primary-color; }.line { position: absolute; left: 8rpx; top: 28rpx; bottom: 0; width: 2rpx; background: $border-color; }.timeline-copy { flex: 1; padding-bottom: 22rpx; }.timeline-title { display: block; color: $text-color-secondary; font-size: $font-size-sm; }.timeline-time { display: block; margin-top: 7rpx; color: $text-color-disabled; font-size: $font-size-xs; }
.caregiver-profile { display: flex; align-items: center; gap: 16rpx; margin-top: 10rpx; padding-top: 20rpx; border-top: 1rpx solid $divider-color; }.caregiver-avatar { display: flex; align-items: center; justify-content: center; width: 72rpx; height: 72rpx; border-radius: 24rpx; background: $primary-bg; }.caregiver-copy { flex: 1; }.caregiver-name { display: block; color: $text-color; font-size: $font-size-base; font-weight: 600; }.caregiver-phone { color: $text-color-secondary; font-size: $font-size-xs; }.record-row { display: flex; align-items: flex-start; justify-content: space-between; gap: 20rpx; padding: 18rpx 0; border-bottom: 1rpx solid $divider-color; }.record-row:last-child { padding-bottom: 0; border-bottom: none; }.record-title, .record-time, .record-summary { display: block; }.record-title { color: $text-color-secondary; font-size: $font-size-sm; }.record-time { margin-top: 7rpx; color: $text-color-disabled; font-size: $font-size-xs; }.record-summary { max-width: 480rpx; margin-top: 8rpx; color: $text-color-hint; font-size: $font-size-xs; line-height: 1.5; }.record-status { flex-shrink: 0; color: $primary-color; font-size: $font-size-xs; }.service-record { padding-left: 12rpx; border-left: 4rpx solid rgba(58,123,247,.18); }
.bottom-actions { position: fixed; left: 0; right: 0; bottom: 0; display: flex; justify-content: flex-end; gap: 12rpx; padding: 18rpx $spacing-base calc(18rpx + env(safe-area-inset-bottom)); background: rgba(249,251,255,0.93); backdrop-filter: $glass-blur; box-shadow: 0 -6rpx 24rpx rgba(42,91,170,0.08); }.action-btn { height: 66rpx; margin: 0; padding: 0 24rpx; border: 1rpx solid $border-color; border-radius: $radius-round; background: #fff; color: $text-color-secondary; font-size: $font-size-xs; line-height: 64rpx; }.action-btn::after { border: none; }.action-btn.primary { border: none; color: #fff; background: $primary-gradient; }.loading-page { min-height: 100vh; display: flex; align-items: center; justify-content: center; background: $page-gradient; }
</style>
