<template>
  <view class="page-shell"><view class="notice"><u-icon name="info-circle-fill" size="20" color="#FF8A5C" /><text>我们重视每一条反馈，客服将在 24 小时内处理。</text></view><view class="form-card"><text class="section-title">问题类型</text><view class="type-grid"><view v-for="option in complaintStore.TYPE_OPTIONS" :key="option.value" class="type-option" :class="{ active: type === option.value }" @click="type = option.value">{{ option.label }}</view></view><text class="section-title block-title">问题描述</text><textarea v-model="content" class="content-input" maxlength="1000" placeholder="请详细描述遇到的问题，以便我们更快核实处理" /><text class="count">{{ content.length }}/1000</text><text class="section-title block-title">相关截图</text><view class="image-list"><view v-for="(image, index) in images" :key="image" class="image-item"><image :src="image" mode="aspectFill" /><view class="remove-image" @click="images.splice(index, 1)">×</view></view><view v-if="images.length < 6" class="add-image" @click="chooseImages"><u-icon name="camera-fill" size="25" color="#98A5B3" /><text>上传截图</text></view></view></view><u-button type="primary" shape="round" :loading="submitting" class="submit-btn" @click="submit">提交投诉</u-button></view>
</template>
<script setup>
import { ref } from 'vue'; import { onLoad } from '@dcloudio/uni-app'; import { useComplaintStore } from '@/store/complaint.js'; import { useUserStore } from '@/store/user.js'
const complaintStore = useComplaintStore(); const userStore = useUserStore(); const orderId = ref(null); const type = ref(1); const content = ref(''); const images = ref([]); const submitting = ref(false)
onLoad((options) => { orderId.value = Number(options.orderId) }); function chooseImages() { uni.chooseImage({ count: 6 - images.value.length, success: ({ tempFilePaths }) => images.value.push(...tempFilePaths) }) }
async function submit() { if (content.value.trim().length < 5) return uni.showToast({ title: '请详细描述问题', icon: 'none' }); submitting.value = true; try { const uploaded = []; for (const path of images.value) { try { const file = await userStore.uploadFile(path, 'complaint'); uploaded.push(file.fileUrl) } catch { uploaded.push(path) } } await complaintStore.submitComplaint({ orderId: orderId.value, type: type.value, content: content.value.trim(), images: uploaded }); uni.showToast({ title: '投诉已提交', icon: 'success' }); setTimeout(() => uni.redirectTo({ url: '/pages/complaint/complaint-list' }), 700) } finally { submitting.value = false } }
</script>
<style lang="scss" scoped>
.page-shell { min-height: 100vh; padding: 24rpx $spacing-base 60rpx; background: $page-gradient; }.notice { display: flex; align-items: flex-start; gap: 10rpx; padding: 20rpx; border-radius: 20rpx; background: #fff2eb; color: $text-color-secondary; font-size: $font-size-xs; line-height: 1.6; }.form-card { margin-top: 20rpx; padding: 28rpx 24rpx; border: $glass-border-soft; border-radius: 30rpx; background: $surface-gradient; box-shadow: $shadow-sm; }.section-title { display: block; color: $text-color; font-size: $font-size-md; font-weight: 700; }.block-title { margin-top: 34rpx; }.type-grid { display: grid; grid-template-columns: repeat(2,1fr); gap: 14rpx; margin-top: 20rpx; }.type-option { padding: 18rpx; border: 1rpx solid $border-color; border-radius: 18rpx; color: $text-color-secondary; font-size: $font-size-sm; text-align: center; }.type-option.active { border-color: $warning-color; color: $warning-color; background: #fff2eb; }.content-input { width: 100%; height: 190rpx; margin-top: 18rpx; padding: 20rpx; border-radius: 20rpx; background: $bg-color-grey; color: $text-color; font-size: $font-size-sm; line-height: 1.6; }.count { display: block; margin-top: 7rpx; color: $text-color-disabled; font-size: $font-size-xs; text-align: right; }.image-list { display: flex; flex-wrap: wrap; gap: 14rpx; margin-top: 18rpx; }.image-item,.add-image { position: relative; width: 150rpx; height: 150rpx; border-radius: 20rpx; overflow: hidden; }.image-item image { width: 100%; height: 100%; }.remove-image { position: absolute; top: 6rpx; right: 6rpx; width: 38rpx; height: 38rpx; border-radius: 50%; background: rgba(26,37,48,0.65); color: #fff; font-size: 30rpx; line-height: 34rpx; text-align: center; }.add-image { display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 8rpx; border: 2rpx dashed $border-color; color: $text-color-hint; font-size: $font-size-xs; }.submit-btn { height: 88rpx !important; margin-top: 30rpx; border: none !important; background: linear-gradient(135deg,#ff9a6c,#ff7b55) !important; box-shadow: 0 8rpx 28rpx rgba(255,138,92,0.2); font-weight: 600 !important; }
</style>
